/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
	"time"
)

// DeclareStageProgressRequest struct for DeclareStageProgressRequest
type DeclareStageProgressRequest struct {
	Secret *string `json:"secret,omitempty"`
	Status *DeploymentProvisioningInfoStageStatus `json:"status,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Messages []string `json:"messages,omitempty"`
	ImagePushed *bool `json:"image_pushed,omitempty"`
	InternalFailure *bool `json:"internal_failure,omitempty"`
	RetryableFailure *bool `json:"retryable_failure,omitempty"`
}

// NewDeclareStageProgressRequest instantiates a new DeclareStageProgressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeclareStageProgressRequest() *DeclareStageProgressRequest {
	this := DeclareStageProgressRequest{}
	var status DeploymentProvisioningInfoStageStatus = DEPLOYMENTPROVISIONINGINFOSTAGESTATUS_UNKNOWN
	this.Status = &status
	return &this
}

// NewDeclareStageProgressRequestWithDefaults instantiates a new DeclareStageProgressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeclareStageProgressRequestWithDefaults() *DeclareStageProgressRequest {
	this := DeclareStageProgressRequest{}
	var status DeploymentProvisioningInfoStageStatus = DEPLOYMENTPROVISIONINGINFOSTAGESTATUS_UNKNOWN
	this.Status = &status
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetSecret() string {
	if o == nil || isNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetSecretOk() (*string, bool) {
	if o == nil || isNil(o.Secret) {
    return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasSecret() bool {
	if o != nil && !isNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *DeclareStageProgressRequest) SetSecret(v string) {
	o.Secret = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetStatus() DeploymentProvisioningInfoStageStatus {
	if o == nil || isNil(o.Status) {
		var ret DeploymentProvisioningInfoStageStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetStatusOk() (*DeploymentProvisioningInfoStageStatus, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given DeploymentProvisioningInfoStageStatus and assigns it to the Status field.
func (o *DeclareStageProgressRequest) SetStatus(v DeploymentProvisioningInfoStageStatus) {
	o.Status = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetFinishedAt() time.Time {
	if o == nil || isNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.FinishedAt) {
    return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasFinishedAt() bool {
	if o != nil && !isNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *DeclareStageProgressRequest) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetMessages() []string {
	if o == nil || isNil(o.Messages) {
		var ret []string
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetMessagesOk() ([]string, bool) {
	if o == nil || isNil(o.Messages) {
    return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasMessages() bool {
	if o != nil && !isNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []string and assigns it to the Messages field.
func (o *DeclareStageProgressRequest) SetMessages(v []string) {
	o.Messages = v
}

// GetImagePushed returns the ImagePushed field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetImagePushed() bool {
	if o == nil || isNil(o.ImagePushed) {
		var ret bool
		return ret
	}
	return *o.ImagePushed
}

// GetImagePushedOk returns a tuple with the ImagePushed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetImagePushedOk() (*bool, bool) {
	if o == nil || isNil(o.ImagePushed) {
    return nil, false
	}
	return o.ImagePushed, true
}

// HasImagePushed returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasImagePushed() bool {
	if o != nil && !isNil(o.ImagePushed) {
		return true
	}

	return false
}

// SetImagePushed gets a reference to the given bool and assigns it to the ImagePushed field.
func (o *DeclareStageProgressRequest) SetImagePushed(v bool) {
	o.ImagePushed = &v
}

// GetInternalFailure returns the InternalFailure field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetInternalFailure() bool {
	if o == nil || isNil(o.InternalFailure) {
		var ret bool
		return ret
	}
	return *o.InternalFailure
}

// GetInternalFailureOk returns a tuple with the InternalFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetInternalFailureOk() (*bool, bool) {
	if o == nil || isNil(o.InternalFailure) {
    return nil, false
	}
	return o.InternalFailure, true
}

// HasInternalFailure returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasInternalFailure() bool {
	if o != nil && !isNil(o.InternalFailure) {
		return true
	}

	return false
}

// SetInternalFailure gets a reference to the given bool and assigns it to the InternalFailure field.
func (o *DeclareStageProgressRequest) SetInternalFailure(v bool) {
	o.InternalFailure = &v
}

// GetRetryableFailure returns the RetryableFailure field value if set, zero value otherwise.
func (o *DeclareStageProgressRequest) GetRetryableFailure() bool {
	if o == nil || isNil(o.RetryableFailure) {
		var ret bool
		return ret
	}
	return *o.RetryableFailure
}

// GetRetryableFailureOk returns a tuple with the RetryableFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareStageProgressRequest) GetRetryableFailureOk() (*bool, bool) {
	if o == nil || isNil(o.RetryableFailure) {
    return nil, false
	}
	return o.RetryableFailure, true
}

// HasRetryableFailure returns a boolean if a field has been set.
func (o *DeclareStageProgressRequest) HasRetryableFailure() bool {
	if o != nil && !isNil(o.RetryableFailure) {
		return true
	}

	return false
}

// SetRetryableFailure gets a reference to the given bool and assigns it to the RetryableFailure field.
func (o *DeclareStageProgressRequest) SetRetryableFailure(v bool) {
	o.RetryableFailure = &v
}

func (o DeclareStageProgressRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.FinishedAt) {
		toSerialize["finished_at"] = o.FinishedAt
	}
	if !isNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	if !isNil(o.ImagePushed) {
		toSerialize["image_pushed"] = o.ImagePushed
	}
	if !isNil(o.InternalFailure) {
		toSerialize["internal_failure"] = o.InternalFailure
	}
	if !isNil(o.RetryableFailure) {
		toSerialize["retryable_failure"] = o.RetryableFailure
	}
	return json.Marshal(toSerialize)
}

type NullableDeclareStageProgressRequest struct {
	value *DeclareStageProgressRequest
	isSet bool
}

func (v NullableDeclareStageProgressRequest) Get() *DeclareStageProgressRequest {
	return v.value
}

func (v *NullableDeclareStageProgressRequest) Set(val *DeclareStageProgressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeclareStageProgressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeclareStageProgressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeclareStageProgressRequest(val *DeclareStageProgressRequest) *NullableDeclareStageProgressRequest {
	return &NullableDeclareStageProgressRequest{value: val, isSet: true}
}

func (v NullableDeclareStageProgressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeclareStageProgressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


