/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
	"time"
)

// InstanceSnapshot struct for InstanceSnapshot
type InstanceSnapshot struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	AvailableAt *time.Time `json:"available_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	ServiceId *string `json:"service_id,omitempty"`
	DeploymentId *string `json:"deployment_id,omitempty"`
	RegionalDeploymentId *string `json:"regional_deployment_id,omitempty"`
	InstanceId *string `json:"instance_id,omitempty"`
	Status *InstanceSnapshotStatus `json:"status,omitempty"`
	Type *InstanceSnapshotType `json:"type,omitempty"`
	Version *string `json:"version,omitempty"`
	Messages []string `json:"messages,omitempty"`
}

// NewInstanceSnapshot instantiates a new InstanceSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceSnapshot() *InstanceSnapshot {
	this := InstanceSnapshot{}
	var status InstanceSnapshotStatus = INSTANCESNAPSHOTSTATUS_INVALID
	this.Status = &status
	var type_ InstanceSnapshotType = INSTANCESNAPSHOTTYPE_INVALID
	this.Type = &type_
	return &this
}

// NewInstanceSnapshotWithDefaults instantiates a new InstanceSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceSnapshotWithDefaults() *InstanceSnapshot {
	this := InstanceSnapshot{}
	var status InstanceSnapshotStatus = INSTANCESNAPSHOTSTATUS_INVALID
	this.Status = &status
	var type_ InstanceSnapshotType = INSTANCESNAPSHOTTYPE_INVALID
	this.Type = &type_
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InstanceSnapshot) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstanceSnapshot) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetCreatedAt() time.Time {
	if o == nil || isNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *InstanceSnapshot) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetUpdatedAt() time.Time {
	if o == nil || isNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.UpdatedAt) {
    return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *InstanceSnapshot) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetAvailableAt returns the AvailableAt field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetAvailableAt() time.Time {
	if o == nil || isNil(o.AvailableAt) {
		var ret time.Time
		return ret
	}
	return *o.AvailableAt
}

// GetAvailableAtOk returns a tuple with the AvailableAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetAvailableAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.AvailableAt) {
    return nil, false
	}
	return o.AvailableAt, true
}

// HasAvailableAt returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasAvailableAt() bool {
	if o != nil && !isNil(o.AvailableAt) {
		return true
	}

	return false
}

// SetAvailableAt gets a reference to the given time.Time and assigns it to the AvailableAt field.
func (o *InstanceSnapshot) SetAvailableAt(v time.Time) {
	o.AvailableAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetDeletedAt() time.Time {
	if o == nil || isNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.DeletedAt) {
    return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasDeletedAt() bool {
	if o != nil && !isNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *InstanceSnapshot) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetOrganizationId() string {
	if o == nil || isNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetOrganizationIdOk() (*string, bool) {
	if o == nil || isNil(o.OrganizationId) {
    return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasOrganizationId() bool {
	if o != nil && !isNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *InstanceSnapshot) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetProjectId() string {
	if o == nil || isNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetProjectIdOk() (*string, bool) {
	if o == nil || isNil(o.ProjectId) {
    return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasProjectId() bool {
	if o != nil && !isNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *InstanceSnapshot) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetServiceId() string {
	if o == nil || isNil(o.ServiceId) {
		var ret string
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetServiceIdOk() (*string, bool) {
	if o == nil || isNil(o.ServiceId) {
    return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasServiceId() bool {
	if o != nil && !isNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given string and assigns it to the ServiceId field.
func (o *InstanceSnapshot) SetServiceId(v string) {
	o.ServiceId = &v
}

// GetDeploymentId returns the DeploymentId field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetDeploymentId() string {
	if o == nil || isNil(o.DeploymentId) {
		var ret string
		return ret
	}
	return *o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetDeploymentIdOk() (*string, bool) {
	if o == nil || isNil(o.DeploymentId) {
    return nil, false
	}
	return o.DeploymentId, true
}

// HasDeploymentId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasDeploymentId() bool {
	if o != nil && !isNil(o.DeploymentId) {
		return true
	}

	return false
}

// SetDeploymentId gets a reference to the given string and assigns it to the DeploymentId field.
func (o *InstanceSnapshot) SetDeploymentId(v string) {
	o.DeploymentId = &v
}

// GetRegionalDeploymentId returns the RegionalDeploymentId field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetRegionalDeploymentId() string {
	if o == nil || isNil(o.RegionalDeploymentId) {
		var ret string
		return ret
	}
	return *o.RegionalDeploymentId
}

// GetRegionalDeploymentIdOk returns a tuple with the RegionalDeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetRegionalDeploymentIdOk() (*string, bool) {
	if o == nil || isNil(o.RegionalDeploymentId) {
    return nil, false
	}
	return o.RegionalDeploymentId, true
}

// HasRegionalDeploymentId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasRegionalDeploymentId() bool {
	if o != nil && !isNil(o.RegionalDeploymentId) {
		return true
	}

	return false
}

// SetRegionalDeploymentId gets a reference to the given string and assigns it to the RegionalDeploymentId field.
func (o *InstanceSnapshot) SetRegionalDeploymentId(v string) {
	o.RegionalDeploymentId = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetInstanceId() string {
	if o == nil || isNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetInstanceIdOk() (*string, bool) {
	if o == nil || isNil(o.InstanceId) {
    return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasInstanceId() bool {
	if o != nil && !isNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *InstanceSnapshot) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetStatus() InstanceSnapshotStatus {
	if o == nil || isNil(o.Status) {
		var ret InstanceSnapshotStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetStatusOk() (*InstanceSnapshotStatus, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InstanceSnapshotStatus and assigns it to the Status field.
func (o *InstanceSnapshot) SetStatus(v InstanceSnapshotStatus) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetType() InstanceSnapshotType {
	if o == nil || isNil(o.Type) {
		var ret InstanceSnapshotType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetTypeOk() (*InstanceSnapshotType, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given InstanceSnapshotType and assigns it to the Type field.
func (o *InstanceSnapshot) SetType(v InstanceSnapshotType) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetVersion() string {
	if o == nil || isNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetVersionOk() (*string, bool) {
	if o == nil || isNil(o.Version) {
    return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasVersion() bool {
	if o != nil && !isNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *InstanceSnapshot) SetVersion(v string) {
	o.Version = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *InstanceSnapshot) GetMessages() []string {
	if o == nil || isNil(o.Messages) {
		var ret []string
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSnapshot) GetMessagesOk() ([]string, bool) {
	if o == nil || isNil(o.Messages) {
    return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *InstanceSnapshot) HasMessages() bool {
	if o != nil && !isNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []string and assigns it to the Messages field.
func (o *InstanceSnapshot) SetMessages(v []string) {
	o.Messages = v
}

func (o InstanceSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !isNil(o.AvailableAt) {
		toSerialize["available_at"] = o.AvailableAt
	}
	if !isNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !isNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !isNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !isNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !isNil(o.DeploymentId) {
		toSerialize["deployment_id"] = o.DeploymentId
	}
	if !isNil(o.RegionalDeploymentId) {
		toSerialize["regional_deployment_id"] = o.RegionalDeploymentId
	}
	if !isNil(o.InstanceId) {
		toSerialize["instance_id"] = o.InstanceId
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !isNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceSnapshot struct {
	value *InstanceSnapshot
	isSet bool
}

func (v NullableInstanceSnapshot) Get() *InstanceSnapshot {
	return v.value
}

func (v *NullableInstanceSnapshot) Set(val *InstanceSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceSnapshot(val *InstanceSnapshot) *NullableInstanceSnapshot {
	return &NullableInstanceSnapshot{value: val, isSet: true}
}

func (v NullableInstanceSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


