/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
	"fmt"
)

// EgressPolicyMode the model 'EgressPolicyMode'
type EgressPolicyMode string

// List of EgressPolicyMode
const (
	EGRESSPOLICYMODE_DEFAULT EgressPolicyMode = "EGRESS_POLICY_MODE_DEFAULT"
	EGRESSPOLICYMODE_DENY_ALL EgressPolicyMode = "EGRESS_POLICY_MODE_DENY_ALL"
)

// All allowed values of EgressPolicyMode enum
var AllowedEgressPolicyModeEnumValues = []EgressPolicyMode{
	"EGRESS_POLICY_MODE_DEFAULT",
	"EGRESS_POLICY_MODE_DENY_ALL",
}

func (v *EgressPolicyMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EgressPolicyMode(value)
	for _, existing := range AllowedEgressPolicyModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EgressPolicyMode", value)
}

// NewEgressPolicyModeFromValue returns a pointer to a valid EgressPolicyMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEgressPolicyModeFromValue(v string) (*EgressPolicyMode, error) {
	ev := EgressPolicyMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EgressPolicyMode: valid values are %v", v, AllowedEgressPolicyModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EgressPolicyMode) IsValid() bool {
	for _, existing := range AllowedEgressPolicyModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EgressPolicyMode value
func (v EgressPolicyMode) Ptr() *EgressPolicyMode {
	return &v
}

type NullableEgressPolicyMode struct {
	value *EgressPolicyMode
	isSet bool
}

func (v NullableEgressPolicyMode) Get() *EgressPolicyMode {
	return v.value
}

func (v *NullableEgressPolicyMode) Set(val *EgressPolicyMode) {
	v.value = val
	v.isSet = true
}

func (v NullableEgressPolicyMode) IsSet() bool {
	return v.isSet
}

func (v *NullableEgressPolicyMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEgressPolicyMode(val *EgressPolicyMode) *NullableEgressPolicyMode {
	return &NullableEgressPolicyMode{value: val, isSet: true}
}

func (v NullableEgressPolicyMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEgressPolicyMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

