/*
 * Koyeb Rest API
 *
 * The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// GetStackRevisionReply struct for GetStackRevisionReply
type GetStackRevisionReply struct {
	Revision *StackRevision `json:"revision,omitempty"`
}

// NewGetStackRevisionReply instantiates a new GetStackRevisionReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStackRevisionReply() *GetStackRevisionReply {
	this := GetStackRevisionReply{}
	return &this
}

// NewGetStackRevisionReplyWithDefaults instantiates a new GetStackRevisionReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStackRevisionReplyWithDefaults() *GetStackRevisionReply {
	this := GetStackRevisionReply{}
	return &this
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *GetStackRevisionReply) GetRevision() StackRevision {
	if o == nil || o.Revision == nil {
		var ret StackRevision
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStackRevisionReply) GetRevisionOk() (*StackRevision, bool) {
	if o == nil || o.Revision == nil {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *GetStackRevisionReply) HasRevision() bool {
	if o != nil && o.Revision != nil {
		return true
	}

	return false
}

// SetRevision gets a reference to the given StackRevision and assigns it to the Revision field.
func (o *GetStackRevisionReply) SetRevision(v StackRevision) {
	o.Revision = &v
}

func (o GetStackRevisionReply) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Revision != nil {
		toSerialize["revision"] = o.Revision
	}
	return json.Marshal(toSerialize)
}

type NullableGetStackRevisionReply struct {
	value *GetStackRevisionReply
	isSet bool
}

func (v NullableGetStackRevisionReply) Get() *GetStackRevisionReply {
	return v.value
}

func (v *NullableGetStackRevisionReply) Set(val *GetStackRevisionReply) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStackRevisionReply) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStackRevisionReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStackRevisionReply(val *GetStackRevisionReply) *NullableGetStackRevisionReply {
	return &NullableGetStackRevisionReply{value: val, isSet: true}
}

func (v NullableGetStackRevisionReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStackRevisionReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


