/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// DeploymentScalingTargetAverageCPU struct for DeploymentScalingTargetAverageCPU
type DeploymentScalingTargetAverageCPU struct {
	Value *int64 `json:"value,omitempty"`
}

// NewDeploymentScalingTargetAverageCPU instantiates a new DeploymentScalingTargetAverageCPU object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentScalingTargetAverageCPU() *DeploymentScalingTargetAverageCPU {
	this := DeploymentScalingTargetAverageCPU{}
	return &this
}

// NewDeploymentScalingTargetAverageCPUWithDefaults instantiates a new DeploymentScalingTargetAverageCPU object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentScalingTargetAverageCPUWithDefaults() *DeploymentScalingTargetAverageCPU {
	this := DeploymentScalingTargetAverageCPU{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DeploymentScalingTargetAverageCPU) GetValue() int64 {
	if o == nil || isNil(o.Value) {
		var ret int64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentScalingTargetAverageCPU) GetValueOk() (*int64, bool) {
	if o == nil || isNil(o.Value) {
    return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DeploymentScalingTargetAverageCPU) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int64 and assigns it to the Value field.
func (o *DeploymentScalingTargetAverageCPU) SetValue(v int64) {
	o.Value = &v
}

func (o DeploymentScalingTargetAverageCPU) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentScalingTargetAverageCPU struct {
	value *DeploymentScalingTargetAverageCPU
	isSet bool
}

func (v NullableDeploymentScalingTargetAverageCPU) Get() *DeploymentScalingTargetAverageCPU {
	return v.value
}

func (v *NullableDeploymentScalingTargetAverageCPU) Set(val *DeploymentScalingTargetAverageCPU) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentScalingTargetAverageCPU) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentScalingTargetAverageCPU) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentScalingTargetAverageCPU(val *DeploymentScalingTargetAverageCPU) *NullableDeploymentScalingTargetAverageCPU {
	return &NullableDeploymentScalingTargetAverageCPU{value: val, isSet: true}
}

func (v NullableDeploymentScalingTargetAverageCPU) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentScalingTargetAverageCPU) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


