/*
 * Koyeb Rest API
 *
 * The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// CreateStore struct for CreateStore
type CreateStore struct {
	Name *string `json:"name,omitempty"`
	Region *string `json:"region,omitempty"`
	Type *string `json:"type,omitempty"`
	With *map[string]interface{} `json:"with,omitempty"`
}

// NewCreateStore instantiates a new CreateStore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStore() *CreateStore {
	this := CreateStore{}
	return &this
}

// NewCreateStoreWithDefaults instantiates a new CreateStore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStoreWithDefaults() *CreateStore {
	this := CreateStore{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateStore) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStore) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateStore) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateStore) SetName(v string) {
	o.Name = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CreateStore) GetRegion() string {
	if o == nil || o.Region == nil {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStore) GetRegionOk() (*string, bool) {
	if o == nil || o.Region == nil {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CreateStore) HasRegion() bool {
	if o != nil && o.Region != nil {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *CreateStore) SetRegion(v string) {
	o.Region = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateStore) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStore) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateStore) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateStore) SetType(v string) {
	o.Type = &v
}

// GetWith returns the With field value if set, zero value otherwise.
func (o *CreateStore) GetWith() map[string]interface{} {
	if o == nil || o.With == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.With
}

// GetWithOk returns a tuple with the With field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStore) GetWithOk() (*map[string]interface{}, bool) {
	if o == nil || o.With == nil {
		return nil, false
	}
	return o.With, true
}

// HasWith returns a boolean if a field has been set.
func (o *CreateStore) HasWith() bool {
	if o != nil && o.With != nil {
		return true
	}

	return false
}

// SetWith gets a reference to the given map[string]interface{} and assigns it to the With field.
func (o *CreateStore) SetWith(v map[string]interface{}) {
	o.With = &v
}

func (o CreateStore) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Region != nil {
		toSerialize["region"] = o.Region
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.With != nil {
		toSerialize["with"] = o.With
	}
	return json.Marshal(toSerialize)
}

type NullableCreateStore struct {
	value *CreateStore
	isSet bool
}

func (v NullableCreateStore) Get() *CreateStore {
	return v.value
}

func (v *NullableCreateStore) Set(val *CreateStore) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStore) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStore(val *CreateStore) *NullableCreateStore {
	return &NullableCreateStore{value: val, isSet: true}
}

func (v NullableCreateStore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


