/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// GetPersistentVolumeReply struct for GetPersistentVolumeReply
type GetPersistentVolumeReply struct {
	Volume *PersistentVolume `json:"volume,omitempty"`
}

// NewGetPersistentVolumeReply instantiates a new GetPersistentVolumeReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPersistentVolumeReply() *GetPersistentVolumeReply {
	this := GetPersistentVolumeReply{}
	return &this
}

// NewGetPersistentVolumeReplyWithDefaults instantiates a new GetPersistentVolumeReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPersistentVolumeReplyWithDefaults() *GetPersistentVolumeReply {
	this := GetPersistentVolumeReply{}
	return &this
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *GetPersistentVolumeReply) GetVolume() PersistentVolume {
	if o == nil || isNil(o.Volume) {
		var ret PersistentVolume
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersistentVolumeReply) GetVolumeOk() (*PersistentVolume, bool) {
	if o == nil || isNil(o.Volume) {
    return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *GetPersistentVolumeReply) HasVolume() bool {
	if o != nil && !isNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given PersistentVolume and assigns it to the Volume field.
func (o *GetPersistentVolumeReply) SetVolume(v PersistentVolume) {
	o.Volume = &v
}

func (o GetPersistentVolumeReply) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	return json.Marshal(toSerialize)
}

type NullableGetPersistentVolumeReply struct {
	value *GetPersistentVolumeReply
	isSet bool
}

func (v NullableGetPersistentVolumeReply) Get() *GetPersistentVolumeReply {
	return v.value
}

func (v *NullableGetPersistentVolumeReply) Set(val *GetPersistentVolumeReply) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPersistentVolumeReply) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPersistentVolumeReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPersistentVolumeReply(val *GetPersistentVolumeReply) *NullableGetPersistentVolumeReply {
	return &NullableGetPersistentVolumeReply{value: val, isSet: true}
}

func (v NullableGetPersistentVolumeReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPersistentVolumeReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


