/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// UpdateOrganizationNameRequest struct for UpdateOrganizationNameRequest
type UpdateOrganizationNameRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewUpdateOrganizationNameRequest instantiates a new UpdateOrganizationNameRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationNameRequest() *UpdateOrganizationNameRequest {
	this := UpdateOrganizationNameRequest{}
	return &this
}

// NewUpdateOrganizationNameRequestWithDefaults instantiates a new UpdateOrganizationNameRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationNameRequestWithDefaults() *UpdateOrganizationNameRequest {
	this := UpdateOrganizationNameRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateOrganizationNameRequest) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationNameRequest) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateOrganizationNameRequest) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateOrganizationNameRequest) SetName(v string) {
	o.Name = &v
}

func (o UpdateOrganizationNameRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateOrganizationNameRequest struct {
	value *UpdateOrganizationNameRequest
	isSet bool
}

func (v NullableUpdateOrganizationNameRequest) Get() *UpdateOrganizationNameRequest {
	return v.value
}

func (v *NullableUpdateOrganizationNameRequest) Set(val *UpdateOrganizationNameRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationNameRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationNameRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationNameRequest(val *UpdateOrganizationNameRequest) *NullableUpdateOrganizationNameRequest {
	return &NullableUpdateOrganizationNameRequest{value: val, isSet: true}
}

func (v NullableUpdateOrganizationNameRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationNameRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


