/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// Mesh Mesh groups the mesh scope selector and the (optional) custom mesh name. Kept inside NetworkPolicy so scope/name and other network-policy dimensions (egress, future inbound) live together.
type Mesh struct {
	Scope *MeshScope `json:"scope,omitempty"`
	// Custom mesh name — required when scope is MESH_SCOPE_CUSTOM, ignored otherwise. Combined with the workspace ID server-side to ensure the same custom name in different workspaces never collides.
	Name *string `json:"name,omitempty"`
}

// NewMesh instantiates a new Mesh object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMesh() *Mesh {
	this := Mesh{}
	var scope MeshScope = MESHSCOPE_UNSPECIFIED
	this.Scope = &scope
	return &this
}

// NewMeshWithDefaults instantiates a new Mesh object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeshWithDefaults() *Mesh {
	this := Mesh{}
	var scope MeshScope = MESHSCOPE_UNSPECIFIED
	this.Scope = &scope
	return &this
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *Mesh) GetScope() MeshScope {
	if o == nil || isNil(o.Scope) {
		var ret MeshScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mesh) GetScopeOk() (*MeshScope, bool) {
	if o == nil || isNil(o.Scope) {
    return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *Mesh) HasScope() bool {
	if o != nil && !isNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given MeshScope and assigns it to the Scope field.
func (o *Mesh) SetScope(v MeshScope) {
	o.Scope = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Mesh) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mesh) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Mesh) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Mesh) SetName(v string) {
	o.Name = &v
}

func (o Mesh) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableMesh struct {
	value *Mesh
	isSet bool
}

func (v NullableMesh) Get() *Mesh {
	return v.value
}

func (v *NullableMesh) Set(val *Mesh) {
	v.value = val
	v.isSet = true
}

func (v NullableMesh) IsSet() bool {
	return v.isSet
}

func (v *NullableMesh) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMesh(val *Mesh) *NullableMesh {
	return &NullableMesh{value: val, isSet: true}
}

func (v NullableMesh) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMesh) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


