/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
	"fmt"
)

// MeshScope MeshScope selects which set of services can communicate over the mesh. Only meaningful when the mesh is on (i.e. DeploymentMesh is ENABLED, or AUTO and the service is eligible). UNSPECIFIED defers to the organization-level default (workspace-scoped since KOYEB-6062, legacy organizations opted back to organization scope via use_organization_level_mesh).   - MESH_SCOPE_ORGANIZATION: Private communication between services in the same organization (mesh label k-<orgId>).  - MESH_SCOPE_WORKSPACE: Private communication between services in the same workspace/project (mesh label pr_<projectId>).  - MESH_SCOPE_APP: Private communication between services in the same app (mesh label app_<appId>).  - MESH_SCOPE_CUSTOM: Private communication between services in the same workspace that share the same NetworkPolicy.mesh.name. Server-computed label is scoped by workspace, so the same custom name in different workspaces never collides.
type MeshScope string

// List of MeshScope
const (
	MESHSCOPE_UNSPECIFIED MeshScope = "MESH_SCOPE_UNSPECIFIED"
	MESHSCOPE_ORGANIZATION MeshScope = "MESH_SCOPE_ORGANIZATION"
	MESHSCOPE_WORKSPACE MeshScope = "MESH_SCOPE_WORKSPACE"
	MESHSCOPE_APP MeshScope = "MESH_SCOPE_APP"
	MESHSCOPE_CUSTOM MeshScope = "MESH_SCOPE_CUSTOM"
)

// All allowed values of MeshScope enum
var AllowedMeshScopeEnumValues = []MeshScope{
	"MESH_SCOPE_UNSPECIFIED",
	"MESH_SCOPE_ORGANIZATION",
	"MESH_SCOPE_WORKSPACE",
	"MESH_SCOPE_APP",
	"MESH_SCOPE_CUSTOM",
}

func (v *MeshScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MeshScope(value)
	for _, existing := range AllowedMeshScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MeshScope", value)
}

// NewMeshScopeFromValue returns a pointer to a valid MeshScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMeshScopeFromValue(v string) (*MeshScope, error) {
	ev := MeshScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MeshScope: valid values are %v", v, AllowedMeshScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MeshScope) IsValid() bool {
	for _, existing := range AllowedMeshScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MeshScope value
func (v MeshScope) Ptr() *MeshScope {
	return &v
}

type NullableMeshScope struct {
	value *MeshScope
	isSet bool
}

func (v NullableMeshScope) Get() *MeshScope {
	return v.value
}

func (v *NullableMeshScope) Set(val *MeshScope) {
	v.value = val
	v.isSet = true
}

func (v NullableMeshScope) IsSet() bool {
	return v.isSet
}

func (v *NullableMeshScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeshScope(val *MeshScope) *NullableMeshScope {
	return &NullableMeshScope{value: val, isSet: true}
}

func (v NullableMeshScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeshScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

