/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// DeactivateOrganizationRequest struct for DeactivateOrganizationRequest
type DeactivateOrganizationRequest struct {
	// if set to true, skip_confirmation will directly start the deactivation process, without sending a confirmation email beforehand.
	SkipConfirmation *bool `json:"skip_confirmation,omitempty"`
}

// NewDeactivateOrganizationRequest instantiates a new DeactivateOrganizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeactivateOrganizationRequest() *DeactivateOrganizationRequest {
	this := DeactivateOrganizationRequest{}
	return &this
}

// NewDeactivateOrganizationRequestWithDefaults instantiates a new DeactivateOrganizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeactivateOrganizationRequestWithDefaults() *DeactivateOrganizationRequest {
	this := DeactivateOrganizationRequest{}
	return &this
}

// GetSkipConfirmation returns the SkipConfirmation field value if set, zero value otherwise.
func (o *DeactivateOrganizationRequest) GetSkipConfirmation() bool {
	if o == nil || isNil(o.SkipConfirmation) {
		var ret bool
		return ret
	}
	return *o.SkipConfirmation
}

// GetSkipConfirmationOk returns a tuple with the SkipConfirmation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeactivateOrganizationRequest) GetSkipConfirmationOk() (*bool, bool) {
	if o == nil || isNil(o.SkipConfirmation) {
    return nil, false
	}
	return o.SkipConfirmation, true
}

// HasSkipConfirmation returns a boolean if a field has been set.
func (o *DeactivateOrganizationRequest) HasSkipConfirmation() bool {
	if o != nil && !isNil(o.SkipConfirmation) {
		return true
	}

	return false
}

// SetSkipConfirmation gets a reference to the given bool and assigns it to the SkipConfirmation field.
func (o *DeactivateOrganizationRequest) SetSkipConfirmation(v bool) {
	o.SkipConfirmation = &v
}

func (o DeactivateOrganizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.SkipConfirmation) {
		toSerialize["skip_confirmation"] = o.SkipConfirmation
	}
	return json.Marshal(toSerialize)
}

type NullableDeactivateOrganizationRequest struct {
	value *DeactivateOrganizationRequest
	isSet bool
}

func (v NullableDeactivateOrganizationRequest) Get() *DeactivateOrganizationRequest {
	return v.value
}

func (v *NullableDeactivateOrganizationRequest) Set(val *DeactivateOrganizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeactivateOrganizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeactivateOrganizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeactivateOrganizationRequest(val *DeactivateOrganizationRequest) *NullableDeactivateOrganizationRequest {
	return &NullableDeactivateOrganizationRequest{value: val, isSet: true}
}

func (v NullableDeactivateOrganizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeactivateOrganizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


