/*
Koyeb Rest API

The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// GetInstanceSnapshotReply struct for GetInstanceSnapshotReply
type GetInstanceSnapshotReply struct {
	InstanceSnapshot *InstanceSnapshot `json:"instance_snapshot,omitempty"`
}

// NewGetInstanceSnapshotReply instantiates a new GetInstanceSnapshotReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInstanceSnapshotReply() *GetInstanceSnapshotReply {
	this := GetInstanceSnapshotReply{}
	return &this
}

// NewGetInstanceSnapshotReplyWithDefaults instantiates a new GetInstanceSnapshotReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInstanceSnapshotReplyWithDefaults() *GetInstanceSnapshotReply {
	this := GetInstanceSnapshotReply{}
	return &this
}

// GetInstanceSnapshot returns the InstanceSnapshot field value if set, zero value otherwise.
func (o *GetInstanceSnapshotReply) GetInstanceSnapshot() InstanceSnapshot {
	if o == nil || isNil(o.InstanceSnapshot) {
		var ret InstanceSnapshot
		return ret
	}
	return *o.InstanceSnapshot
}

// GetInstanceSnapshotOk returns a tuple with the InstanceSnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInstanceSnapshotReply) GetInstanceSnapshotOk() (*InstanceSnapshot, bool) {
	if o == nil || isNil(o.InstanceSnapshot) {
    return nil, false
	}
	return o.InstanceSnapshot, true
}

// HasInstanceSnapshot returns a boolean if a field has been set.
func (o *GetInstanceSnapshotReply) HasInstanceSnapshot() bool {
	if o != nil && !isNil(o.InstanceSnapshot) {
		return true
	}

	return false
}

// SetInstanceSnapshot gets a reference to the given InstanceSnapshot and assigns it to the InstanceSnapshot field.
func (o *GetInstanceSnapshotReply) SetInstanceSnapshot(v InstanceSnapshot) {
	o.InstanceSnapshot = &v
}

func (o GetInstanceSnapshotReply) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.InstanceSnapshot) {
		toSerialize["instance_snapshot"] = o.InstanceSnapshot
	}
	return json.Marshal(toSerialize)
}

type NullableGetInstanceSnapshotReply struct {
	value *GetInstanceSnapshotReply
	isSet bool
}

func (v NullableGetInstanceSnapshotReply) Get() *GetInstanceSnapshotReply {
	return v.value
}

func (v *NullableGetInstanceSnapshotReply) Set(val *GetInstanceSnapshotReply) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInstanceSnapshotReply) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInstanceSnapshotReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInstanceSnapshotReply(val *GetInstanceSnapshotReply) *NullableGetInstanceSnapshotReply {
	return &NullableGetInstanceSnapshotReply{value: val, isSet: true}
}

func (v NullableGetInstanceSnapshotReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInstanceSnapshotReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


