/*
 * Koyeb Rest API
 *
 * The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package koyeb

import (
	"encoding/json"
)

// ListServiceRevisionsReply struct for ListServiceRevisionsReply
type ListServiceRevisionsReply struct {
	Revisions *[]ServiceRevisionListItem `json:"revisions,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Count *int64 `json:"count,omitempty"`
}

// NewListServiceRevisionsReply instantiates a new ListServiceRevisionsReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListServiceRevisionsReply() *ListServiceRevisionsReply {
	this := ListServiceRevisionsReply{}
	return &this
}

// NewListServiceRevisionsReplyWithDefaults instantiates a new ListServiceRevisionsReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListServiceRevisionsReplyWithDefaults() *ListServiceRevisionsReply {
	this := ListServiceRevisionsReply{}
	return &this
}

// GetRevisions returns the Revisions field value if set, zero value otherwise.
func (o *ListServiceRevisionsReply) GetRevisions() []ServiceRevisionListItem {
	if o == nil || o.Revisions == nil {
		var ret []ServiceRevisionListItem
		return ret
	}
	return *o.Revisions
}

// GetRevisionsOk returns a tuple with the Revisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceRevisionsReply) GetRevisionsOk() (*[]ServiceRevisionListItem, bool) {
	if o == nil || o.Revisions == nil {
		return nil, false
	}
	return o.Revisions, true
}

// HasRevisions returns a boolean if a field has been set.
func (o *ListServiceRevisionsReply) HasRevisions() bool {
	if o != nil && o.Revisions != nil {
		return true
	}

	return false
}

// SetRevisions gets a reference to the given []ServiceRevisionListItem and assigns it to the Revisions field.
func (o *ListServiceRevisionsReply) SetRevisions(v []ServiceRevisionListItem) {
	o.Revisions = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ListServiceRevisionsReply) GetLimit() int64 {
	if o == nil || o.Limit == nil {
		var ret int64
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceRevisionsReply) GetLimitOk() (*int64, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ListServiceRevisionsReply) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int64 and assigns it to the Limit field.
func (o *ListServiceRevisionsReply) SetLimit(v int64) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ListServiceRevisionsReply) GetOffset() int64 {
	if o == nil || o.Offset == nil {
		var ret int64
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceRevisionsReply) GetOffsetOk() (*int64, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ListServiceRevisionsReply) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int64 and assigns it to the Offset field.
func (o *ListServiceRevisionsReply) SetOffset(v int64) {
	o.Offset = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListServiceRevisionsReply) GetCount() int64 {
	if o == nil || o.Count == nil {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceRevisionsReply) GetCountOk() (*int64, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListServiceRevisionsReply) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *ListServiceRevisionsReply) SetCount(v int64) {
	o.Count = &v
}

func (o ListServiceRevisionsReply) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Revisions != nil {
		toSerialize["revisions"] = o.Revisions
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableListServiceRevisionsReply struct {
	value *ListServiceRevisionsReply
	isSet bool
}

func (v NullableListServiceRevisionsReply) Get() *ListServiceRevisionsReply {
	return v.value
}

func (v *NullableListServiceRevisionsReply) Set(val *ListServiceRevisionsReply) {
	v.value = val
	v.isSet = true
}

func (v NullableListServiceRevisionsReply) IsSet() bool {
	return v.isSet
}

func (v *NullableListServiceRevisionsReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListServiceRevisionsReply(val *ListServiceRevisionsReply) *NullableListServiceRevisionsReply {
	return &NullableListServiceRevisionsReply{value: val, isSet: true}
}

func (v NullableListServiceRevisionsReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListServiceRevisionsReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


